
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ASYNC_JOBS=1
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000

  worker:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ASYNC_JOBS=1
    depends_on:
      - redis
      - api
    command: python -c "from rq import Worker; from app.jobs import get_queue; w = Worker(['validation', 'pack_generation'], connection=get_queue().connection); w.work()"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  redis_data:
